// <auto-generated />
using Campany.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Campany.DAL.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20230425145839_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Campany.DAL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "dept 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "dept 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "dept 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "dept 4"
                        });
                });

            modelBuilder.Entity("Campany.DAL.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Isaac"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Damon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Miriam"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Terence"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Roosevelt"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Eduardo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wilbert"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tasha"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Max"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bridget"
                        });
                });

            modelBuilder.Entity("Campany.DAL.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Hematology",
                            Name = "ticket1"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Description = "Neurology",
                            Name = "ticket2"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Description = "Pediatrics",
                            Name = "ticket3"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Description = "Hematology",
                            Name = "ticket4"
                        });
                });

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.Property<int>("DevelopersId")
                        .HasColumnType("int");

                    b.Property<int>("TicketsId")
                        .HasColumnType("int");

                    b.HasKey("DevelopersId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("DeveloperTicket");
                });

            modelBuilder.Entity("Campany.DAL.Ticket", b =>
                {
                    b.HasOne("Campany.DAL.Department", "department")
                        .WithMany("tickets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.HasOne("Campany.DAL.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Campany.DAL.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Campany.DAL.Department", b =>
                {
                    b.Navigation("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
